BigSchool/BigSchool/Controllers/Api/CoursesController.cs
using BigSchool.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace BigSchool.Controllers.Api
{
    public class CoursesController : ApiController
    {
        public ApplicationDbContext  _dbContext { get; set; }
        public CoursesController()
        {
            _dbContext = new ApplicationDbContext();
        }
        [HttpDelete]
        public IHttpActionResult Cancel (int id)
        {
            var userId = User.Identity.GetUserId();
            var course = _dbContext.Courses.Single(c => c.Id == id && c.LecturerId == userId);
            if (course.IsCanceled)
                return NotFound();
            course.IsCanceled = true;
            _dbContext.SaveChanges();
            return Ok();
        }
    }
}

BigSchool/BigSchool/Controllers/CoursesController.cs
using BigSchool.Models;
using BigSchool.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BigSchool.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        public CoursesController()
        {
            _dbContext = new ApplicationDbContext();
        }
        // GET: Courses
        //public ActionResult Create()
        //{
            //var viewModel = new CourseViewModel
            //{
               // Categories = _dbContext.Categories.ToList(),
                //Heading = "Add Course"
                
            //};
            //return View(viewModel);
       // }
        public ActionResult Create(CourseViewModel viewModel)
        {
            if (!ModelState.IsValid)
           {
                viewModel.Categories = _dbContext.Categories.ToList();
                return View("Create", viewModel);
            }
            var course = new Course
            {
                LecturerId = User.Identity.GetUserId(),
                DateTime = viewModel.GetDateTime(),
                CategoryId = viewModel.Category,
                Place = viewModel.place,
                
            };
            _dbContext.Courses.Add(course);
            _dbContext.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
 
       [Authorize]
        public ActionResult Attending()
        {
            var userId = User.Identity.GetUserId();
            var courses = _dbContext.Attendances
                .Where(a => a.AttendeeId == userId)
                .Select(a => a.Course)
                .Include(l => l.Lecturer)
                .Include(l => l.Category)
                .ToList();
            var viewModel = new CourseViewModel
            {
                UpcommingCourses = courses,
                ShowAction = User.Identity.IsAuthenticated
            };
            return View(viewModel);

        }
       [Authorize]
        public ActionResult Mine()
        {
            var userId = User.Identity.GetUserId();
            var courses = _dbContext.Courses
                .Where(c => c.LecturerId == userId && c.DateTime > DateTime.Now)
                .Include(l => l.Lecturer)
                .Include(c => c.Category)
                .ToList();
            return View(courses);
        }
        [Authorize]
        public ActionResult Edit(int id)
        {
            var userId = User.Identity.GetUserId();
            var course = _dbContext.Courses.Single(c => c.Id == id && c.LecturerId == userId);
            var viewModel = new CourseViewModel
            {
                Categories = _dbContext.Categories.ToList(),
                Date = course.DateTime.ToString("dd/M/yyyy"),
                Time= course .DateTime.ToString("HH:mm"),
                Category = course.CategoryId,
                place = course.Place,
                Heading ="Edit Course",
                Id = course.Id
            };
            return View("Create", viewModel);
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(CourseViewModel viewModel)
        {
            if(!ModelState.IsValid)
            {
                viewModel.Categories = _dbContext.Categories.ToList();
                return View("Create", viewModel);
            }
            var userId = User.Identity.GetUserId();
            var course = _dbContext.Courses.Single(c => c.Id == viewModel.Id && c.LecturerId == userId);

            course.Place = viewModel.place;
            course.DateTime = viewModel.GetDateTime();
            course.CategoryId = viewModel.Category;
            _dbContext.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

BigSchool/BigSchool/Views/Courses/Attending.cshtml
@model BigSchool.ViewModels.CourseViewModel
@{
    ViewBag.Title = "Attending";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Attending</h2>



    <table class="course " style="width:100%;">
        @foreach (var course in Model.UpcommingCourses)
        {
           

            <tr>
                <td>
                    <div class="date ">
                    
                            @course.DateTime.ToString("MM")/
                        
                            @course.DateTime.ToString("dd")
                        
                    </div>
                </td>
                <td>
                    @course.Lecturer.Name
                </td>
                <td>
                    @if (course.IsCanceled)
                    {
                        <span class="label label-warning" >Canceled</span>
                    }
                    @if (Model.ShowAction && !course.IsCanceled)
                    {
                        <button class="btn btn-default btn-sm js-toggle-follow" data-user-id="@course.LecturerId">Follow</button>
                    }
                </td>
                
               
                <td>
                    <br />
                    <span class="category">
                        @course.Category.Name
                    </span>
                </td>

            </tr>
            @*<li>
                <div class="date ">
                    <div class="month">
                        @course.DateTime.ToString("MM")
                    </div>
                    <div class="day">
                        @course.DateTime.ToString("dd")
                    </div>
                </div>
                <div class="details">
                    <span class="lecturer">
                        @course.Lecturer.Name
                        @if (Model.ShowAction)
                        {
                            <button class="btn btn-default btn-sm js-toggle-follow" data-user-id="@course.LecturerId">Follow</button>
                        }
                    </span>
                    <br />
                    <span class="category">
                        @course.Category.Name
                    </span>

                </div>
            </li>*@
        }
        </table>

BigSchool/BigSchool/Views/Courses/Create.cshtml
@model BigSchool.ViewModels.CourseViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Heading</h2>
@using (Html.BeginForm(Model.Action, "Courses"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m=>m.Id)
    <div class="form-group">
        @Html.LabelFor(m => m.place)
        @Html.TextBoxFor(m => m.place, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.place)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Date)
        @Html.TextBoxFor(m => m.Date, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Date)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Time)
        @Html.TextBoxFor(m => m.Time, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Time)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Category)
        @Html.DropDownListFor(m => m.Category,
                 new SelectList(Model.Categories, "Id", "Name"), "", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Category)
    </div>
    <button type="submit" value="Save" class="btn btn-primary">Save</button>
}
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval");
}

BigSchool/BigSchool/Views/Courses/Mine.cshtml
@model IEnumerable<BigSchool.Models.Course>
@{
    ViewBag.Title = "Mine";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Mine</h2>
<ul class="course">
    @foreach (var course in Model)
    {
        <li>
            <div class="date">
                <div class="month">
                    @course.DateTime.ToString("MM")
                </div>
                <div class="day">
                    @course.DateTime.ToString("dd")        
                </div>
            </div>
            <div class="details">
                <span class="lecturer">
                    @course.Lecturer.Name
                </span>
                <br />
                <span class="category">
                    @course.Category.Name
                </span>
               <div class="action">
                   <a href="@Url.Action("Edit","Courses", new  { id = course.Id })">
                        Edit
                   </a>
                   <a href="#" class="js-cancel-course" data-course-id="@course.Id">|Cancel</a>
               </div>
            </div>
        </li>
    }
</ul>
@section scripts
{
    <script>
    

        $(document).ready(function () {
            $(".js-cancel-course").click(function (e) {
                e.preventDefault();
                var link = $(e.target);
                bootbox.confirm({
                    title: "Cancel Cource",
                    message: "Are you sure to cancel?",
                    button: {
                        cancel: {
                            label: '<i class="fa fa-times"></i> Cancel'
                        },
                        confirm: {
                            label: '<i class="fa fa-times"></i> confirm'
                        }
                    },
                    callback: function (result) {
                        if (result) {
                            $.ajax({
                                url: "/api/courses/" + link.attr("data-course-id"),
                                method: "DELETE"
                            })
                                .done(function () {
                                    link.parents("li").fadeOut(function () {
                                        $(this).remove();
                                    });
                                })
                                .fail(function () {
                                    alert("Something failed!");
                                });
                        }
                    }
                });
            });
        });
                   
    </script>
}